### ISSUE TITLE
Library gives error when lunch consume

### ISSUE THREAD

**Issue by cellojaan** [alessandrojp/easy-checkout#9]
Hi. Thanks for your great library.

I wanted to setup this library in my app but gives me error.

I setup like this:

**Builder:**
` //App Billing Build
        BillingContext.Builder builder = new BillingContext.Builder()
                .setContext(getApplicationContext()) // App context
                .setPublicKeyBase64(getString(R.string.application_key))
                .setApiVersion(BillingApi.VERSION_3)
                .setLogger(new SystemLogger());
        builder.build();`

**Consume on click**

**mBillingProcessor.consumePurchase(itemId, new ConsumeItemHandler() {
            @ Override
            public void onSuccess() {
                Toast.makeText(getApplicationContext(), "Purchase OK", Toast.LENGTH_LONG).show();
            }

            @Override
            public void onError(BillingException e) {
                Toast.makeText(getApplicationContext(), "Purchase Error", Toast.LENGTH_LONG).show();
            }
        });**

Gives error:
`Attempt to invoke virtual method 'void jp.alessandro.android.iab.BillingProcessor.consumePurchase(java.lang.String, jp.alessandro.android.iab.handler.ConsumeItemHandler)' on a null object reference`

What's it's mean?
Thanks.

**Comment by alessandrojp** [comment]
@cellojaan Hi
Looking at the code you posted, you call the the build `builder.build()`, but you don't set the `mBillingProcessor`. You must set it first and then call `consumePurchase`.

You should have something similar to this:
```
BillingContext.Builder builder = new BillingContext.Builder()
  .setContext(getApplicationContext()).
  setPublicKeyBase64(getString(R.string.application_key))
  .setApiVersion(BillingApi.VERSION_3)
  .setLogger(new SystemLogger()); 

BillingProcessor processor = builder.build();
processor.consumePurchase(itemId, new ConsumeItemHandler() {
  @ Override
  public void onSuccess() {
    Toast.makeText(getApplicationContext(), "Purchase OK", Toast.LENGTH_LONG).show();
  }
  @Override
  public void onError(BillingException e) {
    Toast.makeText(getApplicationContext(), "Purchase Error", Toast.LENGTH_LONG).show();
  }
});
```

Please let me know if it works?

**Comment by cellojaan** [comment]
It's says like this for processor

**Incompatible types.
Required:
jp.alessandro.android.iab.BillingProcessor
Found:
jp.alessandro.android.iab.BillingContext**

**Comment by cellojaan** [comment]
Can you make a example please for consume?

**Comment by alessandrojp** [comment]
I'm sorry.
You should do this:

```
BillingContext.Builder builder = new BillingContext.Builder()
  .setContext(getApplicationContext()).
  setPublicKeyBase64(getString(R.string.application_key))
  .setApiVersion(BillingApi.VERSION_3)
  .setLogger(new SystemLogger()); 

BillingProcessor processor = new BillingProcessor(builder.build(), null);
processor.consumePurchase(itemId, new ConsumeItemHandler() {
  @ Override
  public void onSuccess() {
    Toast.makeText(getApplicationContext(), "Purchase OK", Toast.LENGTH_LONG).show();
  }
  @Override
  public void onError(BillingException e) {
    Toast.makeText(getApplicationContext(), "Purchase Error", Toast.LENGTH_LONG).show();
  }
});
```
Remember that the second argument I put `null` because you just want to use the `consumePurchase`, if you want to purchase something, you must set the PurchaseHandler.

It also described [here](https://github.com/alessandrojp/android-easy-checkout#sample-sample-app-coming-soon) how to init the billing processor.
Once you init the processor, you can call any action in the library.

**Comment by cellojaan** [comment]
I setup PurchaseHandler and now do not gives error. But also do not onSuccess. Showing onError when click button.

My activity is:
[https://pastebin.com/VPqUZaKr](https://pastebin.com/VPqUZaKr)

I do not know what I did wrong.

**Comment by cellojaan** [comment]
İn your example also gives error when I lunch:

> java.lang.IllegalArgumentException: One or more arguments are missing.

**Comment by alessandrojp** [comment]
The library will not work if you don't upload the apk to the play store.
You cannot just put some dummy data and run it in the develop environment expecting that will work.

You can find more information about how to test your app here:
https://developer.android.com/google/play/billing/billing_testing

Since there is nothing wrong with the library, I'm closing this.

**Comment by cellojaan** [comment]
Hi again. I know it. Normally purchase is working there is no problem only consume is not working and gives errors. I couldn't fix it.

**Comment by cellojaan** [comment]
And I uploaded in store.

**Comment by alessandrojp** [comment]
The `onError` will return you a BillingException if there is something wrong.
Please check the error message to see what is wrong.

**Comment by cellojaan** [comment]
Already I returned error message in onError. But it is stopping app and gives this message in logcat:

java.lang.IllegalArgumentException: One or more arguments are missing.

**Comment by alessandrojp** [comment]
The library is checking the item id and the handler as shown here:
https://github.com/alessandrojp/android-easy-checkout/blob/master/library/src/main/java/jp/alessandro/android/iab/Checker.java#L59-L63

The checker is not doing anything special, so if you are getting that message, you should do a double check in your code again.

**Comment by cellojaan** [comment]
I did not understand what I have to do but that's ok thanks for your
interesting.

If you make a sample about consume I will be happy.

Best Regards.
